# backend/Dockerfile.dev
FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
# generate prisma client for container
RUN npx prisma generate
EXPOSE 5000
# run dev server (ts-node-dev must be in devDeps)
CMD ["npm", "run", "dev"]
